[package]
name = "RustyPlatormer"
version = "0.1.0"
authors = ["Kamil Pituła <kamil.pitula@outlook.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
piston = "0.49.0"
piston2d-graphics = "0.35.0"
pistoncore-glutin_window = "0.63.0"
piston2d-opengl_graphics = "0.69.0"
rand = "0.7.2"
itertools = "0.8.2"
find_folder = "0.3.0"
piston_window = "0.105.0"
serde = {version = "1.0.104", features=["derive"]}
serde_yaml = "0.8"
interpolation = "0.2.0"